-- En caso de crearse una base de datos en especifico ejecutar el siguiente código
CREATE DATABASE USER_MANAGER
GO

USE USER_MANAGER
GO

-- Crear el esquema
CREATE SCHEMA UMA
GO

CREATE TABLE [UMA].[GENDER](
	ID_GENDER INT PRIMARY KEY IDENTITY(1,1),
	GENDER NVARCHAR(50) NOT NULL
);

CREATE TABLE [UMA].[USERS](
	ID_USER INT PRIMARY KEY IDENTITY(1,1),
	NAME_USER NVARCHAR(100) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	ID_GENDER INT,
	CONSTRAINT FK_USERS_GENDER FOREIGN KEY (ID_GENDER) REFERENCES [UMA].[GENDER](ID_GENDER)
);

-- Generacion de consultas
SELECT * FROM [UMA].[GENDER];
SELECT * FROM [UMA].[USERS];